// <auto-generated />
using System;
using Aurora.Platform.Tenancy.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aurora.Platform.Tenancy.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.DatabaseCluster", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("id");

                    b.Property<string>("AdminSecretRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("admin_secret_ref");

                    b.Property<string>("AppSecretRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("app_secret_ref");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<string>("MaintenanceDatabase")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("maintenance_database");

                    b.Property<int>("MaxTenants")
                        .HasColumnType("integer")
                        .HasColumnName("max_tenants");

                    b.Property<string>("MigratorSecretRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("migrator_secret_ref");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_database_cluster");

                    b.HasAlternateKey("Id", "Region")
                        .HasName("ak_database_cluster_id_region");

                    b.HasIndex("Region", "State")
                        .HasDatabaseName("ix_database_cluster_region_state");

                    b.ToTable("database_cluster", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_database_cluster_id_well_formed", "id ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_database_cluster_max_tenants_positive", "max_tenants > 0");

                            t.HasCheckConstraint("ck_database_cluster_port_is_tcp_port", "port BETWEEN 1 AND 65535");

                            t.HasCheckConstraint("ck_database_cluster_secret_refs_are_references", "admin_secret_ref !~ '[=;[:space:]]' AND migrator_secret_ref !~ '[=;[:space:]]' AND app_secret_ref !~ '[=;[:space:]]'");

                            t.HasCheckConstraint("ck_database_cluster_state", "state IN ('Accepting', 'Closed', 'Retired')");
                        });
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.InstalledPackage", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("PackageId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("package_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("InstalledBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("installed_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "PackageId")
                        .HasName("pk_installed_package");

                    b.ToTable("installed_package", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_installed_package_id_well_formed", "package_id ~ '^[a-z][a-z0-9_]*$'");

                            t.HasCheckConstraint("ck_installed_package_state", "state IN ('Installing', 'Active', 'Deactivated', 'UpgradePending', 'Failed')");
                        });
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_subscription");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subscription_tenant_id");

                    b.ToTable("subscription", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_subscription_ends_after_it_starts", "valid_to IS NULL OR valid_to > valid_from");

                            t.HasCheckConstraint("ck_subscription_seats_positive", "seats > 0");
                        });
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("ClusterId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cluster_id");

                    b.Property<int?>("CoreSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("core_schema_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("database_name");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DeletionDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_due_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Plan")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan");

                    b.Property<string>("ResidencyRegion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("residency_region");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_key");

                    b.HasIndex("ClusterId", "ResidencyRegion")
                        .HasDatabaseName("ix_tenant_cluster_id_residency_region");

                    b.HasIndex("State", "LastActivityAt")
                        .HasDatabaseName("ix_tenant_state_last_activity_at");

                    b.ToTable("tenant", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_deleted_at_matches_state", "(state = 'Deleted') = (deleted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_tenant_key_well_formed", "key ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*$' AND length(key) >= 3");

                            t.HasCheckConstraint("ck_tenant_routing_present_unless_deleted", "state = 'Deleted' OR (display_name IS NOT NULL AND cluster_id IS NOT NULL AND database_name IS NOT NULL AND residency_region IS NOT NULL AND plan IS NOT NULL)");

                            t.HasCheckConstraint("ck_tenant_state", "state IN ('Provisioning', 'ProvisioningFailed', 'Active', 'Suspended', 'SchemaBlocked', 'Exporting', 'PendingDeletion', 'Deleted')");
                        });
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.TenantHost", b =>
                {
                    b.Property<string>("Host")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Host")
                        .HasName("pk_tenant_host");

                    b.HasIndex(new[] { "TenantId" }, "ix_tenant_host_tenant_id");

                    b.HasIndex(new[] { "TenantId" }, "ux_tenant_host_primary")
                        .IsUnique()
                        .HasFilter("is_primary");

                    b.ToTable("tenant_host", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_host_lower_case", "host = lower(host)");
                        });
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.InstalledPackage", b =>
                {
                    b.HasOne("Aurora.Platform.Tenancy.Catalog.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_installed_package_tenant");
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.Subscription", b =>
                {
                    b.HasOne("Aurora.Platform.Tenancy.Catalog.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_tenant");
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.Tenant", b =>
                {
                    b.HasOne("Aurora.Platform.Tenancy.Catalog.DatabaseCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId", "ResidencyRegion")
                        .HasPrincipalKey("Id", "Region")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenant_cluster_in_region");
                });

            modelBuilder.Entity("Aurora.Platform.Tenancy.Catalog.TenantHost", b =>
                {
                    b.HasOne("Aurora.Platform.Tenancy.Catalog.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_host_tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
