using System;
using Aurora.Platform.Tenancy.Contracts;
using Microsoft.EntityFrameworkCore.Migrations;

// The migration fixtures for MIG1 and MIG2. Each is a real EF Core Migration carrying the real
// [Migration] id and the real [MigrationSafety] attribute, and its SQL is generated by Npgsql's own
// generator exactly as a production migration's is - so when a rule fires on one, it fires on the
// SQL the runner would execute, not on a test author's idea of it. Ids start at 2099 so they can
// never collide with a scaffolded one. They are types, not tests: nothing here runs against a
// database, and every production rule is blind to them (ProductionPopulationTests).
namespace Aurora.Architecture.Tests.Fixtures.Violations;

/// <summary>An Expand whose <c>DropColumn()</c> has no raw SQL string anywhere to scan.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b> The link a raw-string scan misses.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: claims Expand while dropping a column through an EF operation.")]
internal sealed class ExpandThatDropsAColumn : Migration
{
    public const string Id = "20990101000001_ExpandThatDropsAColumn";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropColumn(name: "legacy", schema: "sales", table: "invoice");
}

/// <summary>An Expand whose <c>RenameColumn()</c> becomes <c>ALTER TABLE … RENAME COLUMN</c>.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: claims Expand while renaming a column through an EF operation.")]
internal sealed class ExpandThatRenamesAColumn : Migration
{
    public const string Id = "20990101000002_ExpandThatRenamesAColumn";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.RenameColumn(name: "number", schema: "sales", table: "invoice", newName: "invoice_number");
}

/// <summary>A <c>DROP TABLE</c> inside a <c>DO</c> body: real DDL, one dollar quote down.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: hides a DROP TABLE inside a dollar-quoted body.")]
internal sealed class ExpandHidingADropInADollarQuotedBody : Migration
{
    public const string Id = "20990101000003_ExpandHidingADropInADollarQuotedBody";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DO $body$ BEGIN DROP TABLE sales.invoice; END $body$;");
}

/// <summary>
/// One real <c>drop table</c> in lower case with a comment and a newline between its keywords,
/// beside a <c>DROP TABLE</c> in a string literal and another in a comment. Exactly one finding.
/// </summary>
/// <remarks><b>Deliberately violating fixture (MIG2)</b>, and a false-positive guard at the same time.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: one camouflaged DROP TABLE among two that are only text.")]
internal sealed class ExpandWithACamouflagedDropTable : Migration
{
    public const string Id = "20990101000004_ExpandWithACamouflagedDropTable";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql(
            "INSERT INTO sales.note (text) VALUES ('DROP TABLE sales.invoice'); -- DROP TABLE sales.invoice\n"
            + "drop\n  /* DROP TABLE sales.invoice */ table\n  sales.invoice;");
}

/// <summary>The same <c>DROP TABLE</c> in a <c>DO</c> body spelled as a single-quoted literal, which is the same statement to PostgreSQL.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b> The first review's B-1: this spelling was reported clean.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: hides a DROP TABLE inside a quoted DO body.")]
internal sealed class ExpandHidingADropInAQuotedBody : Migration
{
    public const string Id = "20990101000023_ExpandHidingADropInAQuotedBody";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DO 'BEGIN DROP TABLE sales.invoice; END';");
}

/// <summary>The look-alike beside it: the same text as data, in a position where a literal is only data.</summary>
/// <remarks><b>Deliberately compliant fixture (MIG2).</b> Reading literals as code only where PostgreSQL does is what keeps this clean.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: procedural-looking text stored as data.")]
internal sealed class ExpandWithAProceduralLookAlikeInData : Migration
{
    public const string Id = "20990101000024_ExpandWithAProceduralLookAlikeInData";

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("INSERT INTO sales.note (text) VALUES ('BEGIN DROP TABLE sales.invoice; END');");
        migrationBuilder.Sql("INSERT INTO sales.note (text) VALUES ('a' || 'DROP TABLE sales.invoice');");
        migrationBuilder.Sql("INSERT INTO sales.note (text) VALUES ('BEGIN '\n'DROP TABLE sales.invoice; END');");
    }
}

/// <summary>The same <c>DROP TABLE</c> split across two adjacent literals, which PostgreSQL joins into one body.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b> The second review's N-2: the first half was read, the second never.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: hides a DROP TABLE across two concatenated literals of a DO body.")]
internal sealed class ExpandHidingADropInAConcatenatedBody : Migration
{
    public const string Id = "20990101000027_ExpandHidingADropInAConcatenatedBody";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DO 'BEGIN DR'\n'OP TABLE sales.invoice; END';");
}

/// <summary>An Expand that switches a guard trigger to replica mode, so it never fires for an ordinary write.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b> The second review's N-1: <c>DISABLE</c> by another spelling, and the reverse of B-19's <c>ENABLE ALWAYS</c>.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: disarms an append-only guard with ENABLE REPLICA TRIGGER.")]
internal sealed class ExpandThatDisarmsAGuardTrigger : Migration
{
    public const string Id = "20990101000028_ExpandThatDisarmsAGuardTrigger";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("ALTER TABLE catalog.operator_audit_event ENABLE REPLICA TRIGGER trg_operator_audit_event_append_only;");
}

/// <summary>A DataOnly migration whose statement head is allowed but which carries a procedural body as a value.</summary>
/// <remarks>
/// <b>Deliberately violating fixture (MIG2).</b> The second review's n-3: the body clause of the
/// DataOnly check had no witness of its own, because the only body fixture also had a <c>DO</c> head.
/// </remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.DataOnly, "Fixture: an INSERT carrying a dollar-quoted body.")]
internal sealed class DataOnlyWithABodyUnderAnAllowedHead : Migration
{
    public const string Id = "20990101000029_DataOnlyWithABodyUnderAnAllowedHead";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("INSERT INTO sales.note (text) VALUES ($$BEGIN UPDATE sales.invoice SET total = 0; END$$);");
}

/// <summary>One of two migrations declaring the same id; which of the pair MIG1 names is whichever lost the tie.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1), with <see cref="DuplicateIdTwinB"/>.</b> The second review's n-2: the duplicate-id branch had no witness.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: one of two migrations sharing an id.")]
internal sealed class DuplicateIdTwinA : Migration
{
    public const string Id = "20990101000099_DuplicateId";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("CREATE TABLE sales.twin_a (id integer NOT NULL);");
}

/// <summary>The other half of the duplicate-id pair.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1), with <see cref="DuplicateIdTwinA"/>.</b></remarks>
[Migration(DuplicateIdTwinA.Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: the other of two migrations sharing an id.")]
internal sealed class DuplicateIdTwinB : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("CREATE TABLE sales.twin_b (id integer NOT NULL);");
}

/// <summary>A Contract that runs dynamic SQL: the one category allowed to be destructive, made unreadable.</summary>
/// <remarks>
/// <b>Deliberately unscannable fixture (MIG2).</b> The first review's M-2: an unreadable Contract
/// must be a violation and must not be counted as a permitted destructive statement, or it is
/// indistinguishable from a permitted one.
/// </remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Contract, "Fixture: a Contract whose drop is built at run time.", Contracts = CompliantExpand.Id)]
internal sealed class ContractThatRunsDynamicSql : Migration
{
    public const string Id = "20990101000025_ContractThatRunsDynamicSql";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DO $$ BEGIN EXECUTE 'DROP TABLE sales.stage'; END $$;");
}

/// <summary>A DataOnly migration that calls a function whose body is not here to read.</summary>
/// <remarks><b>Deliberately unscannable fixture (MIG2).</b> Unscannable is a violation for every category, DataOnly included.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.DataOnly, "Fixture: a DataOnly migration calling a user function.")]
internal sealed class DataOnlyThatCallsAUserFunction : Migration
{
    public const string Id = "20990101000026_DataOnlyThatCallsAUserFunction";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("SELECT sales.rebuild_everything();");
}

/// <summary>A harmless statement and a <c>TRUNCATE</c> on one line, in one <c>Sql()</c> call.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: two statements on one line, the second destructive.")]
internal sealed class ExpandWithTwoStatementsOnOneLine : Migration
{
    public const string Id = "20990101000005_ExpandWithTwoStatementsOnOneLine";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("CREATE TABLE sales.a (id integer NOT NULL); TRUNCATE sales.b;");
}

/// <summary><c>ADD COLUMN … NOT NULL</c> with no default: every existing row makes it fail, and N-1 inserts break.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: adds a NOT NULL column with no default.")]
internal sealed class ExpandAddingANotNullColumnWithoutADefault : Migration
{
    public const string Id = "20990101000006_ExpandAddingANotNullColumnWithoutADefault";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("ALTER TABLE sales.invoice ADD COLUMN region text NOT NULL;");
}

/// <summary>A type change and a <c>SET NOT NULL</c> in one <c>ALTER TABLE</c>: two narrowings.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: narrows two columns.")]
internal sealed class ExpandThatNarrowsAColumn : Migration
{
    public const string Id = "20990101000007_ExpandThatNarrowsAColumn";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("ALTER TABLE sales.invoice ALTER COLUMN total TYPE numeric(10,2), ALTER COLUMN region SET NOT NULL;");
}

/// <summary>Dynamic SQL: the <c>DROP TABLE</c> is a string handed to <c>EXECUTE</c> at run time.</summary>
/// <remarks><b>Deliberately unscannable fixture (MIG2).</b> Must be reported as unread, not as clean.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: runs a DROP TABLE through EXECUTE.")]
internal sealed class ExpandThatRunsDynamicSql : Migration
{
    public const string Id = "20990101000008_ExpandThatRunsDynamicSql";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DO $$ BEGIN EXECUTE 'DROP TABLE sales.invoice'; END $$;");
}

/// <summary>A call to a function defined in some earlier migration, whose body is not here to read.</summary>
/// <remarks><b>Deliberately unscannable fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: calls a schema-qualified function.")]
internal sealed class ExpandThatCallsAUserFunction : Migration
{
    public const string Id = "20990101000009_ExpandThatCallsAUserFunction";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("SELECT sales.rebuild_everything();");
}

/// <summary>Text the tokenizer cannot finish: a string literal that never closes.</summary>
/// <remarks><b>Deliberately unscannable fixture (MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: an unterminated literal.")]
internal sealed class ExpandWithAnUnterminatedLiteral : Migration
{
    public const string Id = "20990101000010_ExpandWithAnUnterminatedLiteral";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("INSERT INTO sales.note (text) VALUES ('never closed);");
}

/// <summary>A migration whose <c>Up()</c> throws, so no SQL exists to scan.</summary>
/// <remarks><b>Deliberately unscannable fixture (MIG2).</b> Kept in the population and reported, not dropped from it.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: Up() throws before producing an operation.")]
internal sealed class ExpandWhoseUpThrows : Migration
{
    public const string Id = "20990101000011_ExpandWhoseUpThrows";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        throw new InvalidOperationException("this migration cannot describe itself");
}

/// <summary>A DataOnly migration that creates a table.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b> The category is a lie the SQL exposes.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.DataOnly, "Fixture: claims DataOnly while creating a table.")]
internal sealed class DataOnlyThatCreatesATable : Migration
{
    public const string Id = "20990101000012_DataOnlyThatCreatesATable";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.CreateTable(
            name: "note",
            schema: "sales",
            columns: table => new { id = table.Column<int>(type: "integer", nullable: false) },
            constraints: table => table.PrimaryKey("pk_note", x => x.id));
}

/// <summary>A DataOnly migration whose only statement is a procedural body.</summary>
/// <remarks><b>Deliberately violating fixture (MIG2).</b> Data-only means reviewable at a glance; a body is not.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.DataOnly, "Fixture: a DO body in a DataOnly migration.")]
internal sealed class DataOnlyWithAProceduralBody : Migration
{
    public const string Id = "20990101000013_DataOnlyWithAProceduralBody";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("DO $$ BEGIN UPDATE sales.invoice SET total = 0; END $$;");
}

/// <summary>No <c>[MigrationSafety]</c> at all - and it drops a column, so MIG2 must not let the absence exempt it.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1, MIG2).</b></remarks>
[Migration(Id)]
internal sealed class UnannotatedMigration : Migration
{
    public const string Id = "20990101000014_UnannotatedMigration";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropColumn(name: "legacy", schema: "sales", table: "invoice");
}

/// <summary>Annotated, with a reason that says nothing.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "   ")]
internal sealed class ExpandWithABlankReason : Migration
{
    public const string Id = "20990101000015_ExpandWithABlankReason";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("CREATE TABLE sales.blank (id integer NOT NULL);");
}

/// <summary>A Contract that does not say what it contracts.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1).</b> The release gate has nothing to pair it with.</remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Contract, "Fixture: a Contract naming no Expand.")]
internal sealed class ContractNamingNoExpand : Migration
{
    public const string Id = "20990101000016_ContractNamingNoExpand";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropColumn(name: "legacy", schema: "sales", table: "invoice");
}

/// <summary>A Contract naming an Expand that is not in the population.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Contract, "Fixture: a Contract naming a migration that does not exist.", Contracts = "20990101000000_DoesNotExist")]
internal sealed class ContractNamingAMissingExpand : Migration
{
    public const string Id = "20990101000017_ContractNamingAMissingExpand";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropColumn(name: "legacy", schema: "sales", table: "invoice");
}

/// <summary>A Contract naming a DataOnly migration as the thing it contracts.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Contract, "Fixture: a Contract naming a DataOnly migration.", Contracts = DataOnlyBackfill.Id)]
internal sealed class ContractNamingADataOnlyMigration : Migration
{
    public const string Id = "20990101000018_ContractNamingADataOnlyMigration";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropColumn(name: "legacy", schema: "sales", table: "invoice");
}

/// <summary>An Expand that names something it contracts, which only a Contract may do.</summary>
/// <remarks><b>Deliberately violating fixture (MIG1).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: an Expand with Contracts set.", Contracts = CompliantExpand.Id)]
internal sealed class ExpandNamingAnExpand : Migration
{
    public const string Id = "20990101000019_ExpandNamingAnExpand";

    protected override void Up(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("CREATE TABLE sales.extra (id integer NOT NULL);");
}

/// <summary>
/// The shapes a real Expand has - the catalog's and the audit trail's - every one of which only
/// looks destructive: a trigger on <c>DELETE OR TRUNCATE</c>, a <c>GRANT … DELETE</c>, an
/// <c>ON DELETE RESTRICT</c>, a <c>DROP NOT NULL</c>, a <c>DROP CONSTRAINT</c>, a trigger bound
/// with <c>EXECUTE FUNCTION</c>, a function body that raises, and text saying <c>DROP TABLE</c>
/// in a literal and in a comment.
/// </summary>
/// <remarks>
/// <b>Deliberately compliant fixture (MIG1, MIG2).</b> Silence on this one is what proves the
/// rule bans ADR-0007's destructive statements and not the design ADR-0007 prescribes; the
/// statement count asserted beside it is what makes the silence meaningful.
/// </remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Expand, "Fixture: every additive shape a real Expand uses, and nothing destructive.")]
internal sealed class CompliantExpand : Migration
{
    public const string Id = "20990101000020_CompliantExpand";

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.EnsureSchema(name: "sales");

        migrationBuilder.CreateTable(
            name: "invoice",
            schema: "sales",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                party_id = table.Column<Guid>(type: "uuid", nullable: true),
                number = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                total = table.Column<decimal>(type: "numeric(19,4)", nullable: false),
                note = table.Column<string>(type: "text", nullable: true),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_invoice", x => x.id);
                table.CheckConstraint("ck_invoice_number_well_formed", "number ~ '^[A-Z0-9-]+$' AND length(number) >= 3");
                table.ForeignKey(
                    name: "fk_invoice_party",
                    column: x => x.party_id,
                    principalSchema: "parties",
                    principalTable: "party",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(name: "ix_invoice_party_id", schema: "sales", table: "invoice", column: "party_id");

        migrationBuilder.AddColumn<string>(name: "region", schema: "sales", table: "invoice", type: "text", nullable: false, defaultValue: "none");

        migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS sales.note (id integer NOT NULL, text text NOT NULL);");
        migrationBuilder.Sql("ALTER TABLE sales.invoice ALTER COLUMN note DROP NOT NULL, DROP CONSTRAINT ck_invoice_number_well_formed;");
        migrationBuilder.Sql(
            "ALTER TABLE sales.invoice ADD CONSTRAINT ex_invoice_no_overlap "
            + "EXCLUDE USING gist (party_id WITH =, daterange(valid_from, valid_to, '[)') WITH &&);");
        migrationBuilder.Sql(
            "CREATE FUNCTION sales.refuse_change() RETURNS trigger LANGUAGE plpgsql AS $$ "
            + "BEGIN RAISE EXCEPTION 'sales.invoice is append-only' USING ERRCODE = '42501'; END $$;");
        migrationBuilder.Sql(
            "CREATE TRIGGER trg_invoice_append_only BEFORE UPDATE OR DELETE OR TRUNCATE ON sales.invoice "
            + "FOR EACH STATEMENT EXECUTE FUNCTION sales.refuse_change();");
        migrationBuilder.Sql("GRANT SELECT, INSERT, DELETE, TRUNCATE ON sales.invoice TO aurora_app; -- not a DROP TABLE");
        migrationBuilder.Sql("INSERT INTO sales.note (id, text) VALUES (1, 'DROP TABLE sales.invoice');");
    }
}

/// <summary>A Contract that drops what <see cref="CompliantExpand"/> made redundant, and names it.</summary>
/// <remarks>
/// <b>Deliberately compliant fixture (MIG1, MIG2).</b> Its three destructive statements are
/// permitted, and counted as permitted, so "no violation" here is shown to mean "seen and allowed"
/// rather than "not scanned".
/// </remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.Contract, "Fixture: drops the column, table and staging rows the Expand replaced.", Contracts = CompliantExpand.Id)]
internal sealed class CompliantContract : Migration
{
    public const string Id = "20990101000021_CompliantContract";

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(name: "legacy", schema: "sales", table: "invoice");
        migrationBuilder.Sql("DROP TABLE sales.legacy_invoice; TRUNCATE sales.stage;");
    }
}

/// <summary>A backfill: an EF <c>InsertData</c> operation and a raw <c>UPDATE</c>, nothing else.</summary>
/// <remarks><b>Deliberately compliant fixture (MIG1, MIG2).</b></remarks>
[Migration(Id)]
[MigrationSafety(MigrationCategory.DataOnly, "Fixture: inserts one row and backfills a column.")]
internal sealed class DataOnlyBackfill : Migration
{
    public const string Id = "20990101000022_DataOnlyBackfill";

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.InsertData(
            schema: "sales", table: "note", columns: ["id", "text"], columnTypes: ["integer", "text"], values: [1, "seeded"]);
        migrationBuilder.Sql("UPDATE sales.invoice SET region = 'none' WHERE region IS NULL;");
    }
}
